### ISSUE TITLE
Logging Framework Milestone

### ISSUE THREAD

**Issue by tanaaKa** [CoalitionArma/Coalition-Reforger-Framework#91]
- [x] Killfeed
  - Embed message per kill/event
  - Instigator and killed
  - Sides
  - Range
  - Weapon
  - Time
- [ ] ORBAT at end of safestart
  - Embed message
  - Groupname, Name, role, @ 
- [ ] Attendance at the end of safestart
  - Logs to database via enfusion db framework
- [ ] Mission log to database
  - Mission name
  - Author
  - Player count per side
  - Time/date
  - ORBAT (maybe)
- [ ] Stats
  - Individual stats
  - Role stats
- [x] CoalitionBOT functionality
  - Reading killfeed file
- [ ] Final: Check if player is registered upon connect into server
